// LTC waveform synthesizer for the on-app generator. Emits a buffer of
// biphase-mark-encoded LTC at a chosen carrier rate (samples-per-frame timing)
// carrying a count generated by a chosen cadence (FF wrap + DF skip).
//
// Carrier and cadence are deliberately separable so the generator can produce
// out-of-spec material — e.g. integer 30 fps timing with a DF-skipping count
// (the "30 DF" case in issue #1), or a 24-cadence count played back at 29.97
// fps timing. Those streams are how we exercise carrierCadenceMismatch().

import { dropPerMin } from "./dropFrame";

const SYNC = [0,0,1,1,1,1,1,1,1,1,1,1,1,1,0,1];

function writeLsbFirst(bits, start, value, nBits) {
  for (let i = 0; i < nBits; i++) bits[start + i] = (value >> i) & 1;
}

// 80-bit LTC frame layout. Mirrors parseFrame() in ltcDecoder.js. User bits
// are all zero — we're generating timecode only.
//
// Frame tens normally uses bits 8, 9 (max FF=39). At 50/60 cadence we extend
// to 3 bits with bit 58 as MSB (wide-LTC convention, see #34 / parseFrame).
// At 24/25/30 cadence bit 58 is BGF1 and must be left at zero — writing it
// as a frame-tens MSB even when FF<40 is harmless arithmetically but wrong
// semantically and would corrupt BGF1 if a future revision sets it.
//
// Polarity-correction bit: bit 27 at 24/30 cadence, bit 59 at 25 cadence.
// Chosen so the zero-bit count across bits 0–63 (everything except the sync
// word) is even, which holds sync-word polarity steady from one frame to the
// next. Not defined for the wide-LTC 50/60 deviation — those positions are
// used for the field-mark flag in frame-pair LTC, and our wide-LTC synth
// has no field-mark, so we leave the bit at 0 at 50/60.
export function encodeFrameBits(hh, mm, ss, ff, dropFrame, cadenceFps = 30) {
  const bits = new Uint8Array(80);
  const frTens = Math.floor(ff / 10);
  writeLsbFirst(bits, 0, ff % 10, 4);
  writeLsbFirst(bits, 8, frTens & 0b11, 2);
  bits[10] = dropFrame ? 1 : 0;
  bits[11] = 0;
  writeLsbFirst(bits, 16, ss % 10, 4);
  writeLsbFirst(bits, 24, Math.floor(ss / 10), 3);
  writeLsbFirst(bits, 32, mm % 10, 4);
  writeLsbFirst(bits, 40, Math.floor(mm / 10), 3);
  writeLsbFirst(bits, 48, hh % 10, 4);
  writeLsbFirst(bits, 56, Math.floor(hh / 10), 2);
  if (cadenceFps >= 50) bits[58] = (frTens >> 2) & 1;
  // Polarity-correction. Compute parity over bits 0..63 with the correction
  // bit currently 0; if the zero-count is odd, set it to 1 to make even.
  let polarityBit = -1;
  if (cadenceFps === 24 || cadenceFps === 30) polarityBit = 27;
  else if (cadenceFps === 25) polarityBit = 59;
  if (polarityBit >= 0) {
    let zeros = 0;
    for (let i = 0; i < 64; i++) if (bits[i] === 0) zeros++;
    if (zeros % 2 === 1) bits[polarityBit] = 1;
  }
  for (let i = 0; i < 16; i++) bits[64 + i] = SYNC[i];
  return bits;
}

// Increment a HH:MM:SS:FF count by one frame, applying DF skip at minute
// boundaries when requested. cadenceFps is the wrap-at value (24, 25, 30,
// 50, 60). The DF rule (skip 00,01 at 30-cadence; 00,01,02,03 at 60-cadence)
// is applied at every minute that isn't a multiple of 10.
export function nextTc(hh, mm, ss, ff, cadenceFps, dropFrame) {
  ff++;
  if (ff >= cadenceFps) {
    ff = 0;
    ss++;
    if (ss >= 60) {
      ss = 0;
      mm++;
      if (mm >= 60) {
        mm = 0;
        hh = (hh + 1) % 24;
      }
      if (dropFrame && mm % 10 !== 0) {
        ff = dropPerMin(cadenceFps);
      }
    }
  }
  return { hh, mm, ss, ff };
}

// Convert an 80-bit array to biphase-mark samples at the requested
// samples-per-bit. A transition occurs at every bit boundary; a "1" bit adds
// an extra mid-bit transition. samplesPerBit may be fractional — the
// transition schedule is computed in floating point and the sample index is
// floored on writeout.
function biphaseEncode(bits, samplesPerBit, amplitude) {
  const totalSamples = Math.round(bits.length * samplesPerBit);
  const out = new Float32Array(totalSamples);
  // Sorted list of sample indices where the level should flip.
  const transitions = [];
  for (let i = 0; i < bits.length; i++) {
    const bitStart = i * samplesPerBit;
    transitions.push(bitStart);
    if (bits[i] === 1) transitions.push(bitStart + samplesPerBit / 2);
  }
  let level = 1;
  let tIdx = 0;
  for (let s = 0; s < totalSamples; s++) {
    while (tIdx < transitions.length && transitions[tIdx] <= s) {
      level = -level;
      tIdx++;
    }
    out[s] = level * amplitude;
  }
  return out;
}

// Generate a Float32 LTC audio buffer.
//   sampleRate:   target rate (AudioContext.sampleRate)
//   carrierFps:   timing — how many frames-per-second the bit clock encodes.
//                 Independent of cadenceFps; can be any positive number, but
//                 the decoder will only lock when within ±3% of one of its
//                 candidate rates (24/25/30/50/60).
//   cadenceFps:   counting wrap value (24/25/30/50/60).
//   dropFrame:    apply DF skip at minute boundaries (count behaviour).
//   dfFlag:       value to write into bit 10 of every frame. Defaults to
//                 `dropFrame` for spec-conformant output. Pass an explicit
//                 boolean to force a mismatch (e.g. DF skip enabled but flag
//                 cleared, or NDF count with flag asserted) so the
//                 dfFlagMatchesObservedCadence check can be exercised.
//   durationSec:  total buffer length.
//   levelDbFS:    output level. -18 is SMPTE nominal.
//   start:        { hh, mm, ss, ff } starting timecode.
export function buildLtcAudioBuffer({
  sampleRate,
  carrierFps,
  cadenceFps,
  dropFrame,
  dfFlag,
  durationSec = 120,
  levelDbFS = -18,
  start = { hh: 0, mm: 0, ss: 0, ff: 0 },
}) {
  const flagBit = dfFlag == null ? dropFrame : dfFlag;
  const samplesPerBit = sampleRate / (carrierFps * 80);
  const frameCount = Math.floor(durationSec * carrierFps);
  const totalBits = frameCount * 80;
  const allBits = new Uint8Array(totalBits);
  let { hh, mm, ss, ff } = start;
  for (let f = 0; f < frameCount; f++) {
    const frameBits = encodeFrameBits(hh, mm, ss, ff, flagBit, cadenceFps);
    allBits.set(frameBits, f * 80);
    const next = nextTc(hh, mm, ss, ff, cadenceFps, dropFrame);
    hh = next.hh; mm = next.mm; ss = next.ss; ff = next.ff;
  }
  const amplitude = Math.pow(10, levelDbFS / 20);
  return biphaseEncode(allBits, samplesPerBit, amplitude);
}
